### ISSUE TITLE
Novice looking for help

### ISSUE THREAD

**Issue by iPecory** [starformlabs/stellar-nebulaforge-aws#3]
Hi @talawahtech ,

I deployed the templatestellar/quickstart docker image and it was really simple thanks a lot.
I have some knowledge in JAVA coding but nothing in architecture.
I would like to start creating account in the Core and I don't know where to put my Code.
Please do you have any manual (unix syntax) explaining how to interact with the 3 component (Horizon/Core/DB) and with folders use for the JAVA classes.

Sorry if my questions seem ridiculous ....

iPec

**Comment by talawahtech** [comment]
Hi,

Here are a few helpful links if you are looking to get started interacting with Stellar using Java.

Getting started guide: https://www.stellar.org/developers/guides/get-started/index.html
Java SDK: https://github.com/stellar/java-stellar-sdk
Communities where you can ask questions: https://www.stellar.org/community/

**Comment by iPecory** [comment]
Thanks a lot.
